// GENERATED by Supabase MCP generate_typescript_types (project
// wpkdpukpllxuyqqlxkxf) on 2026-07-03. Do not hand-edit — regenerate after
// every migration.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity: string
          entity_id: string
          id: string
          org_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity: string
          entity_id: string
          id?: string
          org_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity?: string
          entity_id?: string
          id?: string
          org_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_log_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      checklist_completions: {
        Row: {
          completed_at: string
          completed_by: string
          snag_id: string
          step: Database["public"]["Enums"]["checklist_step"]
        }
        Insert: {
          completed_at?: string
          completed_by: string
          snag_id: string
          step: Database["public"]["Enums"]["checklist_step"]
        }
        Update: {
          completed_at?: string
          completed_by?: string
          snag_id?: string
          step?: Database["public"]["Enums"]["checklist_step"]
        }
        Relationships: [
          {
            foreignKeyName: "checklist_completions_completed_by_fkey"
            columns: ["completed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checklist_completions_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
        ]
      }
      corrective_actions: {
        Row: {
          completed_at: string | null
          created_at: string
          description: string
          due_date: string
          id: string
          owner_id: string
          snag_id: string
          status: Database["public"]["Enums"]["corrective_action_status"]
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          description: string
          due_date: string
          id?: string
          owner_id: string
          snag_id: string
          status?: Database["public"]["Enums"]["corrective_action_status"]
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          description?: string
          due_date?: string
          id?: string
          owner_id?: string
          snag_id?: string
          status?: Database["public"]["Enums"]["corrective_action_status"]
        }
        Relationships: [
          {
            foreignKeyName: "corrective_actions_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "corrective_actions_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
        ]
      }
      debrief_attendees: {
        Row: {
          created_at: string
          debrief_id: string
          id: string
          profile_id: string
        }
        Insert: {
          created_at?: string
          debrief_id: string
          id?: string
          profile_id: string
        }
        Update: {
          created_at?: string
          debrief_id?: string
          id?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "debrief_attendees_debrief_id_fkey"
            columns: ["debrief_id"]
            isOneToOne: false
            referencedRelation: "snag_debriefs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "debrief_attendees_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      debrief_findings: {
        Row: {
          created_at: string
          created_by: string
          debrief_id: string
          finding_text: string
          id: string
        }
        Insert: {
          created_at?: string
          created_by: string
          debrief_id: string
          finding_text: string
          id?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          debrief_id?: string
          finding_text?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "debrief_findings_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "debrief_findings_debrief_id_fkey"
            columns: ["debrief_id"]
            isOneToOne: false
            referencedRelation: "snag_debriefs"
            referencedColumns: ["id"]
          },
        ]
      }
      debrief_lessons: {
        Row: {
          created_at: string
          created_by: string
          debrief_id: string
          id: string
          lesson_text: string
        }
        Insert: {
          created_at?: string
          created_by: string
          debrief_id: string
          id?: string
          lesson_text: string
        }
        Update: {
          created_at?: string
          created_by?: string
          debrief_id?: string
          id?: string
          lesson_text?: string
        }
        Relationships: [
          {
            foreignKeyName: "debrief_lessons_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "debrief_lessons_debrief_id_fkey"
            columns: ["debrief_id"]
            isOneToOne: false
            referencedRelation: "snag_debriefs"
            referencedColumns: ["id"]
          },
        ]
      }
      evidence_items: {
        Row: {
          caption: string | null
          captured_at: string
          id: string
          media_path: string
          snag_id: string
          sort_index: number
          uploaded_by: string
        }
        Insert: {
          caption?: string | null
          captured_at?: string
          id?: string
          media_path: string
          snag_id: string
          sort_index?: number
          uploaded_by: string
        }
        Update: {
          caption?: string | null
          captured_at?: string
          id?: string
          media_path?: string
          snag_id?: string
          sort_index?: number
          uploaded_by?: string
        }
        Relationships: [
          {
            foreignKeyName: "evidence_items_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "evidence_items_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      investigation_files: {
        Row: {
          file_path: string
          generated_at: string
          generated_by: string
          id: string
          snag_id: string
        }
        Insert: {
          file_path: string
          generated_at?: string
          generated_by: string
          id?: string
          snag_id: string
        }
        Update: {
          file_path?: string
          generated_at?: string
          generated_by?: string
          id?: string
          snag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "investigation_files_generated_by_fkey"
            columns: ["generated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "investigation_files_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
        ]
      }
      investigations: {
        Row: {
          completed_at: string
          lead_investigator_id: string
          root_cause_text: string
          snag_id: string
        }
        Insert: {
          completed_at?: string
          lead_investigator_id: string
          root_cause_text: string
          snag_id: string
        }
        Update: {
          completed_at?: string
          lead_investigator_id?: string
          root_cause_text?: string
          snag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "investigations_lead_investigator_id_fkey"
            columns: ["lead_investigator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "investigations_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: true
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
        ]
      }
      invites: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string
          org_id: string
          role: Database["public"]["Enums"]["user_role"]
          site_id: string | null
          status: string
          token: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at?: string
          id?: string
          invited_by: string
          org_id: string
          role?: Database["public"]["Enums"]["user_role"]
          site_id?: string | null
          status?: string
          token?: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string
          org_id?: string
          role?: Database["public"]["Enums"]["user_role"]
          site_id?: string | null
          status?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "invites_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      organisations: {
        Row: {
          created_at: string
          id: string
          industry: string | null
          name: string
          plan_tier: string
        }
        Insert: {
          created_at?: string
          id?: string
          industry?: string | null
          name: string
          plan_tier?: string
        }
        Update: {
          created_at?: string
          id?: string
          industry?: string | null
          name?: string
          plan_tier?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          email: string
          id: string
          name: string
          org_id: string
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          created_at?: string
          email: string
          id: string
          name?: string
          org_id: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          name?: string
          org_id?: string
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: [
          {
            foreignKeyName: "profiles_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      rca_why_steps: {
        Row: {
          answer_text: string
          id: string
          rca_id: string
          updated_at: string
          why_index: number
          why_text: string
        }
        Insert: {
          answer_text: string
          id?: string
          rca_id: string
          updated_at?: string
          why_index: number
          why_text: string
        }
        Update: {
          answer_text?: string
          id?: string
          rca_id?: string
          updated_at?: string
          why_index?: number
          why_text?: string
        }
        Relationships: [
          {
            foreignKeyName: "rca_why_steps_rca_id_fkey"
            columns: ["rca_id"]
            isOneToOne: false
            referencedRelation: "snag_rca"
            referencedColumns: ["id"]
          },
        ]
      }
      site_default_owners: {
        Row: {
          owner_id: string
          site_id: string
          updated_at: string
        }
        Insert: {
          owner_id: string
          site_id: string
          updated_at?: string
        }
        Update: {
          owner_id?: string
          site_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "site_default_owners_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "site_default_owners_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: true
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      site_members: {
        Row: {
          created_at: string
          id: string
          site_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          site_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          site_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "site_members_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "site_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      site_supervisors: {
        Row: {
          created_at: string
          site_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          site_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          site_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "site_supervisors_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "site_supervisors_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      sites: {
        Row: {
          created_at: string
          id: string
          location: string | null
          name: string
          org_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          location?: string | null
          name: string
          org_id: string
        }
        Update: {
          created_at?: string
          id?: string
          location?: string | null
          name?: string
          org_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "sites_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
        ]
      }
      snag_debriefs: {
        Row: {
          completed_at: string | null
          created_at: string
          format: Database["public"]["Enums"]["debrief_format"]
          id: string
          snag_id: string
          started_at: string
          started_by: string
          status: Database["public"]["Enums"]["debrief_status"]
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          format: Database["public"]["Enums"]["debrief_format"]
          id?: string
          snag_id: string
          started_at?: string
          started_by: string
          status?: Database["public"]["Enums"]["debrief_status"]
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          format?: Database["public"]["Enums"]["debrief_format"]
          id?: string
          snag_id?: string
          started_at?: string
          started_by?: string
          status?: Database["public"]["Enums"]["debrief_status"]
        }
        Relationships: [
          {
            foreignKeyName: "snag_debriefs_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snag_debriefs_started_by_fkey"
            columns: ["started_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      snag_rca: {
        Row: {
          accepted_at: string | null
          accepted_by: string | null
          assigned_by: string
          assigned_to: string
          created_at: string
          id: string
          rejection_note: string | null
          snag_id: string
          status: Database["public"]["Enums"]["rca_status"]
          submitted_at: string | null
        }
        Insert: {
          accepted_at?: string | null
          accepted_by?: string | null
          assigned_by: string
          assigned_to: string
          created_at?: string
          id?: string
          rejection_note?: string | null
          snag_id: string
          status?: Database["public"]["Enums"]["rca_status"]
          submitted_at?: string | null
        }
        Update: {
          accepted_at?: string | null
          accepted_by?: string | null
          assigned_by?: string
          assigned_to?: string
          created_at?: string
          id?: string
          rejection_note?: string | null
          snag_id?: string
          status?: Database["public"]["Enums"]["rca_status"]
          submitted_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "snag_rca_accepted_by_fkey"
            columns: ["accepted_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snag_rca_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snag_rca_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snag_rca_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
        ]
      }
      snag_views: {
        Row: {
          id: string
          snag_id: string
          user_id: string
          viewed_at: string
        }
        Insert: {
          id?: string
          snag_id: string
          user_id: string
          viewed_at?: string
        }
        Update: {
          id?: string
          snag_id?: string
          user_id?: string
          viewed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "snag_views_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snag_views_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      snags: {
        Row: {
          approver_id: string | null
          assigned_at: string | null
          confirmed_at: string | null
          confirmed_by: string | null
          created_at: string
          description: string | null
          escalated_at: string | null
          escalated_by: string | null
          id: string
          is_notifiable: boolean
          kind: Database["public"]["Enums"]["snag_kind"]
          lane: string
          latitude: number | null
          longitude: number | null
          occurred_at: string
          org_id: string
          owner_id: string | null
          photo_path: string | null
          reference: string
          reporter_id: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          retained_until: string | null
          severity: Database["public"]["Enums"]["snag_severity"] | null
          site_id: string
          status: Database["public"]["Enums"]["snag_status"]
        }
        Insert: {
          approver_id?: string | null
          assigned_at?: string | null
          confirmed_at?: string | null
          confirmed_by?: string | null
          created_at?: string
          description?: string | null
          escalated_at?: string | null
          escalated_by?: string | null
          id?: string
          is_notifiable?: boolean
          kind: Database["public"]["Enums"]["snag_kind"]
          lane?: string
          latitude?: number | null
          longitude?: number | null
          occurred_at?: string
          org_id: string
          owner_id?: string | null
          photo_path?: string | null
          reference?: string
          reporter_id: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          retained_until?: string | null
          severity?: Database["public"]["Enums"]["snag_severity"] | null
          site_id: string
          status?: Database["public"]["Enums"]["snag_status"]
        }
        Update: {
          approver_id?: string | null
          assigned_at?: string | null
          confirmed_at?: string | null
          confirmed_by?: string | null
          created_at?: string
          description?: string | null
          escalated_at?: string | null
          escalated_by?: string | null
          id?: string
          is_notifiable?: boolean
          kind?: Database["public"]["Enums"]["snag_kind"]
          lane?: string
          latitude?: number | null
          longitude?: number | null
          occurred_at?: string
          org_id?: string
          owner_id?: string | null
          photo_path?: string | null
          reference?: string
          reporter_id?: string
          resolution_note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          retained_until?: string | null
          severity?: Database["public"]["Enums"]["snag_severity"] | null
          site_id?: string
          status?: Database["public"]["Enums"]["snag_status"]
        }
        Relationships: [
          {
            foreignKeyName: "snags_approver_id_fkey"
            columns: ["approver_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_confirmed_by_fkey"
            columns: ["confirmed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_escalated_by_fkey"
            columns: ["escalated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_org_id_fkey"
            columns: ["org_id"]
            isOneToOne: false
            referencedRelation: "organisations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "snags_site_id_fkey"
            columns: ["site_id"]
            isOneToOne: false
            referencedRelation: "sites"
            referencedColumns: ["id"]
          },
        ]
      }
      witness_statements: {
        Row: {
          id: string
          locked: boolean
          locked_at: string | null
          snag_id: string
          statement_text: string
          taken_at: string
          taken_by: string
          witness_name: string
        }
        Insert: {
          id?: string
          locked?: boolean
          locked_at?: string | null
          snag_id: string
          statement_text: string
          taken_at?: string
          taken_by: string
          witness_name: string
        }
        Update: {
          id?: string
          locked?: boolean
          locked_at?: string | null
          snag_id?: string
          statement_text?: string
          taken_at?: string
          taken_by?: string
          witness_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "witness_statements_snag_id_fkey"
            columns: ["snag_id"]
            isOneToOne: false
            referencedRelation: "snags"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "witness_statements_taken_by_fkey"
            columns: ["taken_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invite: {
        Args: { p_name: string; p_token: string }
        Returns: undefined
      }
      accept_rca: { Args: { p_rca_id: string }; Returns: undefined }
      add_debrief_attendee: {
        Args: { p_debrief_id: string; p_profile_id: string }
        Returns: string
      }
      add_debrief_finding: {
        Args: { p_debrief_id: string; p_finding_text: string }
        Returns: string
      }
      add_debrief_lesson: {
        Args: { p_debrief_id: string; p_lesson_text: string }
        Returns: string
      }
      add_evidence_item: {
        Args: { p_caption?: string; p_media_path: string; p_snag_id: string }
        Returns: string
      }
      add_site_member: {
        Args: { p_site_id: string; p_user_id: string }
        Returns: undefined
      }
      add_witness_statement: {
        Args: {
          p_snag_id: string
          p_statement_text: string
          p_witness_name: string
        }
        Returns: string
      }
      assign_rca: {
        Args: { p_assignee_id: string; p_snag_id: string }
        Returns: string
      }
      assign_site_supervisor: {
        Args: { p_site_id: string; p_user_id: string }
        Returns: undefined
      }
      assign_snag_owner: {
        Args: { p_owner_id: string; p_snag_id: string }
        Returns: undefined
      }
      can_edit_site: { Args: { p_site_id: string }; Returns: boolean }
      can_view_site: { Args: { p_site_id: string }; Returns: boolean }
      cancel_rca: { Args: { p_rca_id: string }; Returns: undefined }
      complete_checklist_step: {
        Args: {
          p_snag_id: string
          p_step: Database["public"]["Enums"]["checklist_step"]
        }
        Returns: undefined
      }
      complete_corrective_action: {
        Args: { p_action_id: string }
        Returns: undefined
      }
      complete_debrief: { Args: { p_debrief_id: string }; Returns: undefined }
      confirm_snag: { Args: { p_snag_id: string }; Returns: undefined }
      create_corrective_action: {
        Args: {
          p_description: string
          p_due_date: string
          p_owner_id: string
          p_snag_id: string
        }
        Returns: string
      }
      create_organisation_and_owner: {
        Args: { p_name: string; p_org_name: string }
        Returns: string
      }
      create_site: {
        Args: { p_location?: string; p_name: string }
        Returns: string
      }
      create_snag: {
        Args: {
          p_description?: string
          p_kind: Database["public"]["Enums"]["snag_kind"]
          p_latitude?: number
          p_longitude?: number
          p_photo_path?: string
          p_severity?: Database["public"]["Enums"]["snag_severity"]
          p_site_id?: string
        }
        Returns: {
          id: string
          reference: string
        }[]
      }
      current_org_id: { Args: never; Returns: string }
      current_role: {
        Args: never
        Returns: Database["public"]["Enums"]["user_role"]
      }
      delegate_snag_approver: {
        Args: { p_approver_id: string; p_snag_id: string }
        Returns: undefined
      }
      dispatch_rca_notification: {
        Args: { p_event: string; p_rca_id: string }
        Returns: undefined
      }
      dispatch_snag_notification: {
        Args: { p_event: string; p_snag_id: string }
        Returns: undefined
      }
      escalate_snag: { Args: { p_snag_id: string }; Returns: undefined }
      get_invite_preview: {
        Args: { p_token: string }
        Returns: {
          email: string
          expires_at: string
          org_name: string
          role: Database["public"]["Enums"]["user_role"]
          site_name: string
          status: string
        }[]
      }
      invite_user: {
        Args: {
          p_email: string
          p_role: Database["public"]["Enums"]["user_role"]
          p_site_id?: string
        }
        Returns: string
      }
      mark_snag_seen: { Args: { p_snag_id: string }; Returns: undefined }
      my_member_site_ids: { Args: never; Returns: string[] }
      my_supervised_site_ids: { Args: never; Returns: string[] }
      recategorise_snag: {
        Args: {
          p_kind: Database["public"]["Enums"]["snag_kind"]
          p_severity?: Database["public"]["Enums"]["snag_severity"]
          p_snag_id: string
        }
        Returns: undefined
      }
      record_investigation_export: {
        Args: { p_file_path: string; p_snag_id: string }
        Returns: string
      }
      reassign_rca: {
        Args: { p_new_assignee_id: string; p_rca_id: string }
        Returns: undefined
      }
      reject_rca: {
        Args: { p_rca_id: string; p_rejection_note: string }
        Returns: undefined
      }
      remove_site_member: {
        Args: { p_site_id: string; p_user_id: string }
        Returns: undefined
      }
      remove_site_supervisor: {
        Args: { p_site_id: string; p_user_id: string }
        Returns: undefined
      }
      require_debrief_access: {
        Args: { p_debrief_id: string }
        Returns: {
          approver_id: string | null
          assigned_at: string | null
          confirmed_at: string | null
          confirmed_by: string | null
          created_at: string
          description: string | null
          escalated_at: string | null
          escalated_by: string | null
          id: string
          is_notifiable: boolean
          kind: Database["public"]["Enums"]["snag_kind"]
          lane: string
          latitude: number | null
          longitude: number | null
          occurred_at: string
          org_id: string
          owner_id: string | null
          photo_path: string | null
          reference: string
          reporter_id: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          retained_until: string | null
          severity: Database["public"]["Enums"]["snag_severity"] | null
          site_id: string
          status: Database["public"]["Enums"]["snag_status"]
        }
        SetofOptions: {
          from: "*"
          to: "snags"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      require_serious_snag: {
        Args: { p_snag_id: string }
        Returns: {
          approver_id: string | null
          assigned_at: string | null
          confirmed_at: string | null
          confirmed_by: string | null
          created_at: string
          description: string | null
          escalated_at: string | null
          escalated_by: string | null
          id: string
          is_notifiable: boolean
          kind: Database["public"]["Enums"]["snag_kind"]
          lane: string
          latitude: number | null
          longitude: number | null
          occurred_at: string
          org_id: string
          owner_id: string | null
          photo_path: string | null
          reference: string
          reporter_id: string
          resolution_note: string | null
          resolved_at: string | null
          resolved_by: string | null
          retained_until: string | null
          severity: Database["public"]["Enums"]["snag_severity"] | null
          site_id: string
          status: Database["public"]["Enums"]["snag_status"]
        }
        SetofOptions: {
          from: "*"
          to: "snags"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      resolve_snag: {
        Args: { p_note: string; p_snag_id: string }
        Returns: undefined
      }
      save_rca_why: {
        Args: {
          p_answer_text: string
          p_rca_id: string
          p_why_index: number
          p_why_text: string
        }
        Returns: undefined
      }
      set_notifiable_flag: {
        Args: { p_snag_id: string; p_value: boolean }
        Returns: undefined
      }
      set_root_cause: {
        Args: { p_root_cause_text: string; p_snag_id: string }
        Returns: undefined
      }
      set_site_default_owner: {
        Args: { p_owner_id: string; p_site_id: string }
        Returns: undefined
      }
      start_debrief: {
        Args: {
          p_format: Database["public"]["Enums"]["debrief_format"]
          p_snag_id: string
        }
        Returns: string
      }
      submit_rca: { Args: { p_rca_id: string }; Returns: undefined }
      update_snag_status: {
        Args: {
          p_note?: string
          p_snag_id: string
          p_status: Database["public"]["Enums"]["snag_status"]
        }
        Returns: undefined
      }
    }
    Enums: {
      checklist_step:
        | "make_safe"
        | "preserve_scene"
        | "capture_evidence"
        | "identify_witnesses"
        | "find_root_cause"
      corrective_action_status: "open" | "done"
      debrief_format: "hot" | "formal"
      debrief_status: "in_progress" | "completed"
      rca_status:
        | "assigned"
        | "in_progress"
        | "submitted"
        | "accepted"
        | "rejected"
        | "cancelled"
      snag_kind: "fixit" | "improvement" | "hazard" | "incident"
      snag_severity: "minor" | "moderate" | "injury" | "critical"
      snag_status:
        | "flagged"
        | "in_progress"
        | "sorted"
        | "resolved"
        | "rca_pending"
      user_role: "worker" | "supervisor" | "officer_admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      checklist_step: [
        "make_safe",
        "preserve_scene",
        "capture_evidence",
        "identify_witnesses",
        "find_root_cause",
      ],
      corrective_action_status: ["open", "done"],
      debrief_format: ["hot", "formal"],
      debrief_status: ["in_progress", "completed"],
      rca_status: [
        "assigned",
        "in_progress",
        "submitted",
        "accepted",
        "rejected",
        "cancelled",
      ],
      snag_kind: ["fixit", "improvement", "hazard", "incident"],
      snag_severity: ["minor", "moderate", "injury", "critical"],
      snag_status: [
        "flagged",
        "in_progress",
        "sorted",
        "resolved",
        "rca_pending",
      ],
      user_role: ["worker", "supervisor", "officer_admin"],
    },
  },
} as const
